//! Lint: authorship trailers in a commit message or a forge body.
//!
//! Applies to every authored message, not just commits, because a pull-request
//! body never passes through git and so no git hook can ever inspect one. That
//! gap is how tool-advertising trailers reached the forge unnoticed for months.
//!
//! # Two axes, configured independently
//!
//! Provenance is an agent `Co-Authored-By`. It is judged against the glob the
//! active mode permits, which is what lets a genuinely headless run carry the
//! byline that work wants while a run with a human in the loop carries none. A
//! co-author who is a real person is never touched.
//!
//! Adverts are `Generated with [...]`, a session link, a robot emoji. These
//! are not provenance: they are injected by a tool's defaults rather than chosen,
//! they say nothing about who did the work, and they turn a durable public record
//! into a billboard. Denied by default on every surface and in every mode, with
//! their own glob so a project that wants one says so explicitly.
//!
//! The axes are separate because the reasoning differs. Provenance is warranted
//! exactly when nobody was watching; an advert is unwarranted regardless.
//!
//! # Who made the commit
//!
//! A commit authored or committed as an agent makes the provenance claim in a
//! field no message edit reaches, and it carries no trailer to find: commits made
//! under a container's global identity passed every message check for that
//! reason. So the commit's author and committer, when the gate hands them over,
//! are judged on the provenance axis, by the same list of agent identities and
//! against the same glob as a `Co-Authored-By`. An identity the glob permits for
//! the active mode is left alone, and so is one that names no agent on the list.
//! A pull-request body has no author or committer, and is handed none.
//!
//! What an identity is recognised by is one list for the trailer and the
//! identity alike, and it is what only an agent carries: a mailbox an agent
//! commits from, a `[bot]` marker, or a name that is wholly a tool's own name.
//! Never a word that happens to sit inside somebody's name, since a substring
//! match refuses `Devin Smith`, `Claude Monet` and `Haider Ali` on every commit
//! they make, and a vendor's domain is no marker either, so a person writing from
//! one is a person. The one edge left is a person whose whole `user.name` is a
//! tool's name, and `agent_identities` is the remedy, redefined per project.
//! Mockspace's `lib/attribution.sh`, which the review scanner reads, holds the same
//! three kinds of entry, kept in step with this list by hand.
//!
//! # Patterns are configuration
//!
//! The built-in pattern sets are defaults loaded from configuration, not
//! hardcoded rules. A project adds its own via `extra_patterns`, and the shipped
//! `attribution-claude` / `attribution-copilot` presets are just named bundles it
//! can import and then extend.

use std::collections::HashMap;

use mockspace_lint_rules::{AgentMode, Lint, LintError, MessageContext, MessageLint, Severity};

const LINT_NAME: &str = "message-attribution";

/// The default advert patterns, as substrings matched case-insensitively.
///
/// Defaults rather than rules: a project overrides or extends the set. They live
/// here as the shipped baseline so a project that configures nothing still gets
/// the protection, per the principle that a default must fit everyone, and
/// nobody wants a tool advert in their history.
const DEFAULT_ADVERT_PATTERNS: &[&str] = &[
    "generated with [claude",
    "generated with claude code",
    "generated by [claude",
    "co-authored-by: claude code",
    "claude-session:",
    "generated with [copilot",
    "generated with [cursor",
    "generated with [codex",
    "generated with [devin",
    "🤖",
];

/// The default agent identities that make a `Co-Authored-By`, or the author or
/// committer of a commit, provenance rather than a person.
///
/// Three kinds of entry, told apart by their shape (see `names_an_agent`): a
/// tool's own name, matched against the whole of a name; a mailbox an agent
/// commits from, matched whole; and a marker only a bot carries, matched anywhere
/// in the name or the mailbox.
///
/// The tools the review scanner in mockspace's `lib/attribution.sh` names, held to
/// the same test: what only an agent carries. The two lists are kept in step by
/// hand, and the person matrix is in both suites. A word that is also an ordinary
/// name (`jules`, `cody`, `bard`, `kiro`) stays out of the first kind, and one that
/// is in it counts only as the whole of a name, so `Devin AI` is the tool and
/// `Devin Smith` is a person.
const DEFAULT_AGENT_IDENTITIES: &[&str] = &[
    "claude",
    "copilot",
    "chatgpt",
    "gpt",
    "codex",
    "gemini",
    "devin",
    "cursor",
    "aider",
    "amp",
    "grok",
    "windsurf",
    "codeium",
    "tabnine",
    "supermaven",
    "codewhisperer",
    "antigravity",
    "opencode",
    "replit",
    "ghostwriter",
    "phind",
    "deepseek",
    "qwen",
    "ollama",
    "swe-agent",
    "noreply@anthropic.com",
    "noreply@openai.com",
    "copilot@github.com",
    "cursoragent@cursor.com",
    "agent@cursor.com",
    "[bot]",
];

pub struct MessageAttribution {
    /// Glob a byline must match under [`AgentMode::Assistant`]. Empty permits
    /// none, which is the correct default: the work is the human's.
    assistant_glob:   String,
    /// Glob a byline must match under [`AgentMode::Autonomous`].
    autonomous_glob:  String,
    /// Glob an advert must match to be permitted. Empty permits none.
    advert_glob:      String,
    /// Advert patterns replacing the shipped defaults.
    advert_patterns:  Vec<String>,
    /// Advert patterns added to whatever set is active.
    extra_patterns:   Vec<String>,
    /// Agent identities replacing the shipped defaults.
    agent_identities: Vec<String>,
}

impl Default for MessageAttribution {
    fn default() -> Self {
        Self {
            assistant_glob:   String::new(),
            autonomous_glob:  String::new(),
            advert_glob:      String::new(),
            advert_patterns:  DEFAULT_ADVERT_PATTERNS
                .iter()
                .map(|s| (*s).to_string())
                .collect(),
            extra_patterns:   Vec::new(),
            agent_identities: DEFAULT_AGENT_IDENTITIES
                .iter()
                .map(|s| (*s).to_string())
                .collect(),
        }
    }
}

impl Lint for MessageAttribution {
    fn name(&self) -> &'static str {
        LINT_NAME
    }

    fn description(&self) -> &'static str {
        "authorship trailers and the commit's author and committer match the policy for the active mode, and no tool adverts"
    }

    fn source_only(&self) -> bool {
        false
    }

    fn default_severity(&self) -> Severity {
        Severity::HARD_ERROR
    }

    fn finding_kinds(&self) -> &[&str] {
        &["advert", "byline", "identity", "missing-byline"]
    }

    fn config_keys(&self) -> &[&str] {
        &[
            "assistant",
            "autonomous",
            "adverts",
            "advert_patterns",
            "extra_patterns",
            "agent_identities",
        ]
    }

    fn configure(&mut self, params: &HashMap<String, String>) {
        if let Some(v) = params.get("assistant") {
            self.assistant_glob = v.clone();
        }
        if let Some(v) = params.get("autonomous") {
            self.autonomous_glob = v.clone();
        }
        if let Some(v) = params.get("adverts") {
            self.advert_glob = v.clone();
        }
        if let Some(v) = params.get("advert_patterns") {
            self.advert_patterns = split_list(v);
        }
        if let Some(v) = params.get("extra_patterns") {
            self.extra_patterns = split_list(v);
        }
        if let Some(v) = params.get("agent_identities") {
            self.agent_identities = split_list(v);
        }
    }
}

impl MessageLint for MessageAttribution {
    // Every domain: a commit message, a PR body, an issue or review comment.
    // Leaving this empty is what makes the lint apply to all of them.

    fn check_message(&self, ctx: &MessageContext) -> Vec<LintError> {
        let mut out = Vec::new();
        let permitted = match ctx.mode {
            AgentMode::Assistant => &self.assistant_glob,
            AgentMode::Autonomous => &self.autonomous_glob,
        };

        let mut saw_permitted_byline = false;

        for (n, line) in authored_lines(ctx.message) {
            let lower = line.to_ascii_lowercase();

            // Adverts first: an advert that also looks like a byline is an
            // advert, since `Co-Authored-By: Claude Code` names a tool.
            if self.advert_patterns_active().any(|p| lower.contains(&p)) {
                if !glob_matches(&self.advert_glob, line.trim()) {
                    out.push(finding(
                        ctx,
                        n,
                        "advert",
                        &format!(
                            "tool-advertising trailer, permitted by no configuration here: {}",
                            line.trim()
                        ),
                    ));
                }
                continue;
            }

            // Provenance: only a Co-Authored-By naming an agent is in scope.
            let Some(value) = coauthor_value(line) else { continue };
            if !self.names_an_agent(&value) {
                continue; // a real person; never this lint's business
            }
            if glob_matches(permitted, value.trim()) {
                saw_permitted_byline = true;
            } else {
                out.push(finding(
                    ctx,
                    n,
                    "byline",
                    &if permitted.is_empty() {
                        format!(
                            "an agent byline is permitted in no form under mode `{}`: {}",
                            ctx.mode.as_token(),
                            value.trim()
                        )
                    } else {
                        format!(
                            "the byline does not match the `{}` pattern `{permitted}`: {}",
                            ctx.mode.as_token(),
                            value.trim()
                        )
                    },
                ));
            }
        }

        // Before the requirement below, whose `out.is_empty()` is the point of
        // asking: a refused identity is the more specific thing to fix first.
        self.judge_identity(ctx, permitted, &mut out);

        // Under a mode that configures a required byline, its absence is the
        // violation: headless work with no provenance has no record of author.
        if ctx.mode == AgentMode::Autonomous
            && !self.autonomous_glob.is_empty()
            && !saw_permitted_byline
            && out.is_empty()
        {
            out.push(finding(
                ctx,
                1,
                "missing-byline",
                &format!(
                    "headless work requires a byline matching `{}`, and none is present",
                    self.autonomous_glob
                ),
            ));
        }

        out
    }
}

impl MessageAttribution {
    /// Judge the commit's author and committer on the provenance axis.
    ///
    /// An identity that names an agent is checked against the glob the active
    /// mode permits, exactly as a `Co-Authored-By` value is, and refused where
    /// that does not match. One naming no agent is left alone, and so is a field
    /// the gate did not hand over: absent is not an agent. It does not count as
    /// the byline a headless mode requires, because that requirement is about
    /// the message and the identity is a second record of who made the commit.
    ///
    /// The same identity in both fields is one finding naming both roles, since
    /// a container whose global identity is an agent fills both and two lines
    /// for one fact would double the noise on a push of dozens.
    fn judge_identity(&self, ctx: &MessageContext, permitted: &str, out: &mut Vec<LintError>) {
        let author = ctx.author.map(str::trim).filter(|a| !a.is_empty());
        let committer = ctx.committer.map(str::trim).filter(|c| !c.is_empty());

        // Who is judged, how a finding refers to them, and the verb that agrees.
        let judged: Vec<(&str, &str, &str)> = match (author, committer) {
            (Some(a), Some(c)) if a == c => vec![("the author and committer", "are", a)],
            (a, c) => {
                [("the author", a), ("the committer", c)]
                    .into_iter()
                    .filter_map(|(subject, who)| who.map(|w| (subject, "is", w)))
                    .collect()
            },
        };

        for (subject, verb, who) in judged {
            if !self.names_an_agent(who) || glob_matches(permitted, who) {
                continue;
            }
            let why = if permitted.is_empty() {
                format!("permitted in no form under mode `{}`", ctx.mode.as_token())
            } else {
                format!(
                    "it does not match the `{}` pattern `{permitted}`",
                    ctx.mode.as_token()
                )
            };
            out.push(finding(
                ctx,
                1,
                "identity",
                &format!(
                    "{subject} {verb} an agent identity, {why}: {who}. A commit made with a human in \
                     the loop is the human's: set `user.name` and `user.email` to them and make \
                     the commit again with `--reset-author`."
                ),
            ));
        }
    }

    /// The active advert pattern set: the configured or default base, plus any
    /// extras, all lowercased for case-insensitive matching.
    fn advert_patterns_active(&self) -> impl Iterator<Item = String> + '_ {
        self.advert_patterns
            .iter()
            .chain(self.extra_patterns.iter())
            .map(|p| p.to_ascii_lowercase())
    }

    /// Whether `value`, a `Name <mailbox>` or a bare name or mailbox, is an agent.
    ///
    /// By what only an agent carries, and never by a word that happens to sit
    /// inside somebody's name. Three kinds of entry in `agent_identities`, told
    /// apart by their shape:
    ///
    /// - one holding `@` is a mailbox, matched against the whole of the mailbox;
    /// - one opening with `[` is a marker, matched anywhere in the name or the
    ///   mailbox, since `[bot]` is not something a person writes into either;
    /// - anything else is a tool's own name, which makes the identity an agent's
    ///   only when it is the whole of the name, apart from the words that ride
    ///   along with one: `Claude Opus 4.1`, `GitHub Copilot` and `Devin AI` are
    ///   the tool's, and `Claude Monet` and `Devin Smith` are people.
    ///
    /// A name ending in a parenthesis is read inside it as well, because aider
    /// tags a person's name that way: `Jane Smith (aider)`.
    fn names_an_agent(&self, value: &str) -> bool {
        let (name, mailbox) = split_identity(value);
        let name_lower = name.to_lowercase();
        let mailbox_lower = mailbox.to_lowercase();

        let mut tools: Vec<Vec<String>> = Vec::new();
        for entry in &self.agent_identities {
            let entry = entry.trim().to_lowercase();
            if entry.is_empty() {
                continue;
            }
            if entry.starts_with('[') {
                if name_lower.contains(&entry) || mailbox_lower.contains(&entry) {
                    return true;
                }
            } else if entry.contains('@') {
                if mailbox_lower == entry {
                    return true;
                }
            } else {
                tools.push(core_words(&entry));
            }
        }

        let is_a_tool = |text: &str| {
            let core = core_words(text);
            !core.is_empty() && tools.contains(&core)
        };
        if is_a_tool(&name_lower) {
            return true;
        }
        parenthetical(&name_lower).is_some_and(is_a_tool)
    }
}

/// Words that ride along with a tool's name without being a different name: the
/// model and product words (`Claude Opus`, `Gemini CLI`, `Cursor Agent`) and the
/// vendor (`GitHub Copilot`, `OpenAI Codex`).
const COMPANION_WORDS: &[&str] = &[
    "code",
    "agent",
    "ai",
    "bot",
    "assistant",
    "cli",
    "app",
    "opus",
    "sonnet",
    "haiku",
    "instant",
    "pro",
    "mini",
    "flash",
    "turbo",
    "max",
    "github",
    "anthropic",
    "openai",
    "google",
];

/// The lowercase alphanumeric words of `text`.
fn words_of(text: &str) -> Vec<String> {
    text.split(|c: char| !c.is_alphanumeric())
        .filter(|w| !w.is_empty())
        .map(str::to_lowercase)
        .collect()
}

/// What is left of a name once the words that ride along are taken off, which is
/// what two spellings of one tool's name have in common. A version is a word that
/// opens with a digit. When taking them off would leave nothing the name is kept
/// whole, so `SWE-agent` is a tool and `Agent` on its own is not.
fn core_words(text: &str) -> Vec<String> {
    let all = words_of(text);
    let core: Vec<String> = all
        .iter()
        .filter(|w| {
            !COMPANION_WORDS.contains(&w.as_str())
                && !w.chars().next().is_some_and(|c| c.is_ascii_digit())
        })
        .cloned()
        .collect();
    if core.is_empty() { all } else { core }
}

/// The name and the mailbox of an identity: `Name <mailbox>`, or a bare mailbox
/// when it holds an `@` and no spaces, or a bare name.
fn split_identity(value: &str) -> (&str, &str) {
    let value = value.trim();
    if let (Some(open), Some(close)) = (value.rfind('<'), value.rfind('>')) {
        if open < close {
            return (value[.. open].trim(), value[open + 1 .. close].trim());
        }
    }
    if value.contains('@') && !value.contains(char::is_whitespace) {
        return ("", value);
    }
    (value, "")
}

/// The text inside a closing parenthesis at the end of a name, if there is one.
fn parenthetical(name: &str) -> Option<&str> {
    let inner = name.trim_end().strip_suffix(')')?;
    let open = inner.rfind('(')?;
    Some(&inner[open + 1 ..])
}

/// The authored lines of a message, numbered from one.
///
/// Comment lines and everything from git's verbose-diff scissors marker are
/// dropped, so a trailer quoted in the commented help text, or one appearing in
/// an attached diff, cannot trip the lint.
fn authored_lines(message: &str) -> Vec<(usize, &str)> {
    message
        .split("# ------------------------ >8")
        .next()
        .unwrap_or(message)
        .lines()
        .enumerate()
        .filter(|(_, l)| !l.starts_with('#'))
        .map(|(i, l)| (i + 1, l))
        .collect()
}

/// The value of a `Co-Authored-By` trailer, if this line is one.
fn coauthor_value(line: &str) -> Option<String> {
    let lower = line.to_ascii_lowercase();
    let at = lower.find("co-authored-by:")?;
    Some(line[at + "co-authored-by:".len() ..].to_string())
}

/// Whether `value` matches `pattern`, a glob supporting `*` and `?`.
///
/// An empty pattern matches nothing, which is what makes "configure nothing" mean
/// "permit nothing" rather than "permit everything".
fn glob_matches(pattern: &str, value: &str) -> bool {
    if pattern.is_empty() {
        return false;
    }
    glob_rec(pattern.as_bytes(), value.as_bytes())
}

fn glob_rec(p: &[u8], v: &[u8]) -> bool {
    match (p.first(), v.first()) {
        (None, None) => true,
        (Some(b'*'), _) => {
            // match zero characters, or one more then retry
            glob_rec(&p[1 ..], v) || (!v.is_empty() && glob_rec(p, &v[1 ..]))
        },
        (Some(b'?'), Some(_)) => glob_rec(&p[1 ..], &v[1 ..]),
        (Some(a), Some(b)) if a.eq_ignore_ascii_case(b) => glob_rec(&p[1 ..], &v[1 ..]),
        _ => false,
    }
}

fn split_list(v: &str) -> Vec<String> {
    v.split(',')
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty())
        .collect()
}

fn finding(ctx: &MessageContext, line: usize, kind: &'static str, message: &str) -> LintError {
    LintError::with_finding_kind(
        ctx.origin.to_string(),
        line,
        LINT_NAME,
        message.to_string(),
        Severity::HARD_ERROR,
        kind,
    )
}

#[cfg(test)]
mod tests {
    use mockspace_lint_rules::MessageDomain;

    use super::*;

    fn check(l: &MessageAttribution, mode: AgentMode, msg: &str) -> Vec<String> {
        let ctx = MessageContext {
            domain: MessageDomain::CommitMessage,
            mode,
            message: msg,
            origin: "COMMIT_EDITMSG",
            repo_root: std::path::Path::new("/tmp"),
            invocation: None,
            author: None,
            committer: None,
        };
        l.check_message(&ctx)
            .into_iter()
            .map(|e| e.finding_kind.unwrap_or("none").to_string())
            .collect()
    }

    fn with(pairs: &[(&str, &str)]) -> MessageAttribution {
        let mut l = MessageAttribution::default();
        let mut p = HashMap::new();
        for (k, v) in pairs {
            p.insert((*k).to_string(), (*v).to_string());
        }
        l.configure(&p);
        l
    }

    // --- the deny path, which is the default ---

    #[test]
    fn an_agent_byline_is_denied_when_a_human_was_in_the_loop() {
        let l = MessageAttribution::default();
        assert_eq!(
            check(
                &l,
                AgentMode::Assistant,
                "feat: x\n\nCo-Authored-By: Claude <noreply@anthropic.com>"
            ),
            vec!["byline"]
        );
    }

    #[test]
    fn adverts_are_denied_in_both_modes() {
        let l = MessageAttribution::default();
        for mode in [AgentMode::Assistant, AgentMode::Autonomous] {
            assert_eq!(
                check(
                    &l,
                    mode,
                    "feat: x\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)"
                ),
                vec!["advert"],
                "adverts must be denied under {mode:?}"
            );
        }
    }

    #[test]
    fn a_session_trailer_is_an_advert() {
        let l = MessageAttribution::default();
        assert_eq!(
            check(
                &l,
                AgentMode::Assistant,
                "feat: x\n\nClaude-Session: https://claude.ai/code/session_abc"
            ),
            vec!["advert"]
        );
    }

    #[test]
    fn a_human_co_author_is_never_touched() {
        // The rule is about agent provenance, so a real person's co-authorship
        // must pass in every mode and under every configuration.
        let l = MessageAttribution::default();
        for mode in [AgentMode::Assistant, AgentMode::Autonomous] {
            assert!(
                check(
                    &l,
                    mode,
                    "feat: x\n\nCo-Authored-By: Jane Smith <jane@example.com>"
                )
                .is_empty()
            );
        }
    }

    #[test]
    fn a_github_noreply_human_is_not_an_agent() {
        // `12345+user@users.noreply.github.com` is a real person hiding their
        // address, and matching on `noreply@` would have caught them.
        let l = MessageAttribution::default();
        assert!(
            check(
                &l,
                AgentMode::Assistant,
                "feat: x\n\nCo-Authored-By: Some One <12345+someone@users.noreply.github.com>"
            )
            .is_empty()
        );
    }

    // --- the PERMIT path, which the default config never exercises ---

    #[test]
    fn a_configured_byline_is_permitted_under_headless_mode() {
        // The permit path. Without a test here, a matcher that always denied
        // would pass every other test in this file.
        let l = with(&[("autonomous", "Claude *<noreply@anthropic.com>")]);
        assert!(
            check(
                &l,
                AgentMode::Autonomous,
                "feat: x\n\nCo-Authored-By: Claude Opus <noreply@anthropic.com>"
            )
            .is_empty(),
            "a byline matching the configured glob must be permitted"
        );
    }

    #[test]
    fn the_same_byline_is_still_denied_with_a_human_in_the_loop() {
        // The two modes must genuinely differ, or the predicate is decoration.
        let l = with(&[("autonomous", "Claude *<noreply@anthropic.com>")]);
        assert_eq!(
            check(
                &l,
                AgentMode::Assistant,
                "feat: x\n\nCo-Authored-By: Claude Opus <noreply@anthropic.com>"
            ),
            vec!["byline"]
        );
    }

    #[test]
    fn a_non_matching_byline_is_denied_even_under_headless_mode() {
        // A recognised agent identity that fails the configured glob. Headless
        // mode permits one specific byline, not any byline.
        let l = with(&[("autonomous", "Claude *<noreply@anthropic.com>")]);
        assert_eq!(
            check(
                &l,
                AgentMode::Autonomous,
                "feat: x\n\nCo-Authored-By: Copilot <x@github.test>"
            ),
            vec!["byline"]
        );
    }

    #[test]
    fn an_unrecognised_bot_reads_as_a_human_until_the_list_names_it() {
        // Inherent to matching on identity: a bot nobody has listed is
        // indistinguishable from a person. This is why `agent_identities` is
        // configuration rather than a fixed rule, and the behaviour is asserted
        // so it is a known boundary rather than a surprise.
        let l = MessageAttribution::default();
        assert!(
            check(
                &l,
                AgentMode::Assistant,
                "feat: x\n\nCo-Authored-By: Somebot <x@evil.test>"
            )
            .is_empty()
        );
        let named = with(&[("agent_identities", "claude,somebot")]);
        assert_eq!(
            check(
                &named,
                AgentMode::Assistant,
                "feat: x\n\nCo-Authored-By: Somebot <x@evil.test>"
            ),
            vec!["byline"]
        );
    }

    #[test]
    fn headless_mode_requires_the_byline_it_configures() {
        // Provenance is the point of the mode: work with nobody watching and no
        // byline has no record of who produced it.
        let l = with(&[("autonomous", "Claude *")]);
        assert_eq!(check(&l, AgentMode::Autonomous, "feat: x"), vec![
            "missing-byline"
        ]);
        // and it is not required when the mode does not configure one
        let bare = MessageAttribution::default();
        assert!(check(&bare, AgentMode::Autonomous, "feat: x").is_empty());
    }

    #[test]
    fn a_permitted_advert_glob_lets_one_through() {
        // The advert permit path, so "deny by default" is proven to be a default
        // rather than a hardcoded rule.
        let l = with(&[("adverts", "*Generated with [OurTool]*")]);
        assert!(
            check(
                &l,
                AgentMode::Assistant,
                "feat: x\n\nGenerated with [OurTool](https://x.test)"
            )
            .is_empty()
        );
    }

    // --- configurability ---

    #[test]
    fn a_project_can_add_its_own_advert_pattern() {
        let l = with(&[("extra_patterns", "powered by robotron")]);
        assert_eq!(
            check(&l, AgentMode::Assistant, "feat: x\n\nPowered By Robotron"),
            vec!["advert"]
        );
        // and the shipped defaults still apply alongside it
        assert_eq!(check(&l, AgentMode::Assistant, "feat: x\n\n🤖"), vec![
            "advert"
        ]);
    }

    #[test]
    fn a_project_can_replace_the_default_advert_set_entirely() {
        let l = with(&[("advert_patterns", "only-this")]);
        assert!(check(&l, AgentMode::Assistant, "feat: x\n\n🤖").is_empty());
        assert_eq!(
            check(&l, AgentMode::Assistant, "feat: x\n\nonly-this"),
            vec!["advert"]
        );
    }

    #[test]
    fn a_project_can_redefine_what_counts_as_an_agent() {
        let l = with(&[("agent_identities", "robotron")]);
        // Claude is no longer an agent identity here, so it reads as a human
        assert!(
            check(
                &l,
                AgentMode::Assistant,
                "feat: x\n\nCo-Authored-By: Claude <a@b.test>"
            )
            .is_empty()
        );
        assert_eq!(
            check(
                &l,
                AgentMode::Assistant,
                "feat: x\n\nCo-Authored-By: Robotron <a@b.test>"
            ),
            vec!["byline"]
        );
    }

    // --- robustness ---

    #[test]
    fn commented_lines_and_the_diff_are_not_authored() {
        let l = MessageAttribution::default();
        let msg = "feat: x\n\n# Co-Authored-By: Claude <a@b.test>\n\
                   # ------------------------ >8 ------------------------\n\
                   +Co-Authored-By: Claude <a@b.test>";
        assert!(check(&l, AgentMode::Assistant, msg).is_empty());
    }

    #[test]
    fn the_trailer_key_is_matched_case_insensitively() {
        let l = MessageAttribution::default();
        for form in ["Co-Authored-By:", "co-authored-by:", "CO-AUTHORED-BY:"] {
            assert_eq!(
                check(
                    &l,
                    AgentMode::Assistant,
                    &format!("feat: x\n\n{form} Claude <a@b.test>")
                ),
                vec!["byline"],
                "{form} should be recognised"
            );
        }
    }

    #[test]
    fn an_advert_that_looks_like_a_byline_is_reported_once_as_an_advert() {
        // `Co-Authored-By: Claude Code` names a tool, not a person, so it is an
        // advert. Reporting it twice would be noise.
        let l = MessageAttribution::default();
        assert_eq!(
            check(
                &l,
                AgentMode::Assistant,
                "feat: x\n\nCo-Authored-By: Claude Code <noreply@anthropic.com>"
            ),
            vec!["advert"]
        );
    }

    #[test]
    fn the_glob_supports_star_and_question_mark() {
        assert!(glob_matches("Claude *", "Claude Opus <x@y>"));
        assert!(glob_matches(
            "*<noreply@anthropic.com>",
            "Claude <noreply@anthropic.com>"
        ));
        assert!(glob_matches("a?c", "abc"));
        assert!(!glob_matches("a?c", "ac"));
        assert!(!glob_matches("Claude *", "Somebot <x@y>"));
        // an empty pattern permits nothing, so unconfigured means denied
        assert!(!glob_matches("", "anything"));
    }

    #[test]
    fn every_finding_kind_the_lint_emits_is_declared() {
        let l = with(&[("autonomous", "Claude *")]);
        let declared = l.finding_kinds();
        let mut emitted = Vec::new();
        emitted.extend(check(
            &l,
            AgentMode::Assistant,
            "x\n\nCo-Authored-By: Claude <a@b>",
        ));
        emitted.extend(check(&l, AgentMode::Assistant, "x\n\n🤖"));
        emitted.extend(check(&l, AgentMode::Autonomous, "x"));
        for kind in emitted {
            assert!(
                declared.contains(&kind.as_str()),
                "`{kind}` is not declared"
            );
        }
    }
}
