//! Lint: authorship trailers in a commit message or a forge body.
//!
//! Applies to every authored message, not just commits, because a pull-request
//! body never passes through git and so no git hook can ever inspect one. That
//! gap is how tool-advertising trailers reached the forge unnoticed for months.
//!
//! # Two axes, configured independently
//!
//! Provenance is an agent `Co-Authored-By`. It is judged against the glob the
//! active mode permits, which is what lets a genuinely headless run carry the
//! byline that work wants while a run with a human in the loop carries none. A
//! co-author who is a real person is never touched.
//!
//! Adverts are `Generated with [...]`, a session link, a robot emoji. These
//! are not provenance: they are injected by a tool's defaults rather than chosen,
//! they say nothing about who did the work, and they turn a durable public record
//! into a billboard. Denied by default on every surface and in every mode, with
//! their own glob so a project that wants one says so explicitly.
//!
//! The axes are separate because the reasoning differs. Provenance is warranted
//! exactly when nobody was watching; an advert is unwarranted regardless.
//!
//! # Who made the commit
//!
//! A commit authored or committed as an agent makes the provenance claim in a
//! field no message edit reaches, and it carries no trailer to find: a container
//! whose global git identity is an agent signs every commit it makes as one, and a
//! check that reads only the message passes all of them. So the commit's author and
//! committer, when the gate hands them over, are judged on the provenance axis,
//! by the same recogniser and against the same glob as a `Co-Authored-By`. An
//! identity the glob permits for the active mode is left alone, and so is one that
//! names no agent. A pull-request body has no author or committer, and is handed
//! none.
//!
//! What names an agent is [`agent_identity`](super::agent_identity): what only an
//! agent carries, a marker, a mailbox it commits from, a tag a tool writes into a
//! name, or a name that starts with a tool's own, and never a word that happens to
//! sit inside somebody's name. Four keys carry it: `agent_identities` replaces the
//! whole list, `extra_agent_identities` adds to it, `agent_names` names whole names
//! that are agents whatever the mailbox, and `not_agents` names people who are never
//! to be read as agents. Its lists and verdicts are held to the conformance table
//! that ships with `mockspace-lint-rules`, the one every recogniser of an agent
//! identity is held to.
//!
//! # Patterns are configuration
//!
//! The built-in pattern sets are defaults loaded from configuration, not
//! hardcoded rules. A project adds its own via `extra_patterns`, and the shipped
//! `attribution-claude` / `attribution-copilot` presets are just named bundles it
//! can import and then extend.

use std::collections::HashMap;

use mockspace_lint_rules::{AgentMode, Lint, LintError, MessageContext, MessageLint, Severity};

use super::agent_identity::AgentIdentities;
use crate::util::glob_matches;

const LINT_NAME: &str = "message-attribution";

/// The default advert patterns, as substrings matched case-insensitively.
///
/// Defaults rather than rules: a project overrides or extends the set. They live
/// here as the shipped baseline so a project that configures nothing still gets
/// the protection, per the principle that a default must fit everyone, and
/// nobody wants a tool advert in their history.
const DEFAULT_ADVERT_PATTERNS: &[&str] = &[
    "generated with [claude",
    "generated with claude code",
    "generated by [claude",
    "co-authored-by: claude code",
    "claude-session:",
    "generated with [copilot",
    "generated with [cursor",
    "generated with [codex",
    "generated with [devin",
    "🤖",
];

pub struct MessageAttribution {
    /// Glob a byline must match under [`AgentMode::Assistant`]. Empty permits
    /// none, which is the correct default: the work is the human's.
    assistant_glob:  String,
    /// Glob a byline must match under [`AgentMode::Autonomous`].
    autonomous_glob: String,
    /// Glob an advert must match to be permitted. Empty permits none.
    advert_glob:     String,
    /// Advert patterns replacing the shipped defaults.
    advert_patterns: Vec<String>,
    /// Advert patterns added to whatever set is active.
    extra_patterns:  Vec<String>,
    /// What names an agent, from the shipped defaults and the four keys.
    identities:      AgentIdentities,
}

impl Default for MessageAttribution {
    fn default() -> Self {
        Self {
            assistant_glob:  String::new(),
            autonomous_glob: String::new(),
            advert_glob:     String::new(),
            advert_patterns: DEFAULT_ADVERT_PATTERNS
                .iter()
                .map(|s| (*s).to_string())
                .collect(),
            extra_patterns:  Vec::new(),
            identities:      AgentIdentities::default(),
        }
    }
}

impl Lint for MessageAttribution {
    fn name(&self) -> &'static str {
        LINT_NAME
    }

    fn description(&self) -> &'static str {
        "authorship trailers and the commit's author and committer match the policy for the active mode, and no tool adverts"
    }

    fn source_only(&self) -> bool {
        false
    }

    fn default_severity(&self) -> Severity {
        Severity::HARD_ERROR
    }

    fn finding_kinds(&self) -> &[&str] {
        &["advert", "byline", "identity", "missing-byline"]
    }

    fn config_keys(&self) -> &[&str] {
        &[
            "assistant",
            "autonomous",
            "adverts",
            "advert_patterns",
            "extra_patterns",
            "agent_identities",
            "extra_agent_identities",
            "agent_names",
            "not_agents",
        ]
    }

    fn configure(&mut self, params: &HashMap<String, String>) {
        if let Some(v) = params.get("assistant") {
            self.assistant_glob = v.clone();
        }
        if let Some(v) = params.get("autonomous") {
            self.autonomous_glob = v.clone();
        }
        if let Some(v) = params.get("adverts") {
            self.advert_glob = v.clone();
        }
        if let Some(v) = params.get("advert_patterns") {
            self.advert_patterns = split_list(v);
        }
        if let Some(v) = params.get("extra_patterns") {
            self.extra_patterns = split_list(v);
        }
        if let Some(v) = params.get("agent_identities") {
            self.identities.replace(split_list(v));
        }
        if let Some(v) = params.get("extra_agent_identities") {
            self.identities.extend(split_list(v));
        }
        if let Some(v) = params.get("agent_names") {
            self.identities.name_agents(split_list(v));
        }
        if let Some(v) = params.get("not_agents") {
            self.identities.exclude(split_list(v));
        }
    }
}

impl MessageLint for MessageAttribution {
    // Every domain: a commit message, a PR body, an issue or review comment.
    // Leaving this empty is what makes the lint apply to all of them.

    fn check_message(&self, ctx: &MessageContext) -> Vec<LintError> {
        let mut out = Vec::new();
        let permitted = match ctx.mode {
            AgentMode::Assistant => &self.assistant_glob,
            AgentMode::Autonomous => &self.autonomous_glob,
        };

        let mut saw_permitted_byline = false;

        for (n, line) in authored_lines(ctx.message) {
            let lower = line.to_ascii_lowercase();

            // Adverts first: an advert that also looks like a byline is an
            // advert, since `Co-Authored-By: Claude Code` names a tool.
            if self.advert_patterns_active().any(|p| lower.contains(&p)) {
                if !glob_matches(&self.advert_glob, line.trim()) {
                    out.push(finding(
                        ctx,
                        n,
                        "advert",
                        &format!(
                            "tool-advertising trailer, permitted by no configuration here: {}",
                            line.trim()
                        ),
                    ));
                }
                continue;
            }

            // Provenance: only a Co-Authored-By naming an agent is in scope.
            let Some(value) = coauthor_value(line) else { continue };
            if !self.identities.names_an_agent(&value) {
                continue; // a real person; never this lint's business
            }
            if glob_matches(permitted, value.trim()) {
                saw_permitted_byline = true;
            } else {
                out.push(finding(
                    ctx,
                    n,
                    "byline",
                    &if permitted.is_empty() {
                        format!(
                            "an agent byline is permitted in no form under mode `{}`: {}",
                            ctx.mode.as_token(),
                            value.trim()
                        )
                    } else {
                        format!(
                            "the byline does not match the `{}` pattern `{permitted}`: {}",
                            ctx.mode.as_token(),
                            value.trim()
                        )
                    },
                ));
            }
        }

        // Before the requirement below, whose `out.is_empty()` is the point of
        // asking: a refused identity is the more specific thing to fix first.
        self.judge_identity(ctx, permitted, &mut out);

        // Under a mode that configures a required byline, its absence is the
        // violation: headless work with no provenance has no record of author.
        if ctx.mode == AgentMode::Autonomous
            && !self.autonomous_glob.is_empty()
            && !saw_permitted_byline
            && out.is_empty()
        {
            out.push(finding(
                ctx,
                1,
                "missing-byline",
                &format!(
                    "headless work requires a byline matching `{}`, and none is present",
                    self.autonomous_glob
                ),
            ));
        }

        out
    }
}

impl MessageAttribution {
    /// Judge the commit's author and committer on the provenance axis.
    ///
    /// An identity that names an agent is checked against the glob the active
    /// mode permits, exactly as a `Co-Authored-By` value is, and refused where
    /// that does not match. One naming no agent is left alone, and so is a field
    /// the gate did not hand over: absent is not an agent. It does not count as
    /// the byline a headless mode requires, because that requirement is about
    /// the message and the identity is a second record of who made the commit.
    ///
    /// The same identity in both fields is one finding naming both roles, since
    /// a container whose global identity is an agent fills both and two lines
    /// for one fact would double the noise on a push of dozens.
    fn judge_identity(&self, ctx: &MessageContext, permitted: &str, out: &mut Vec<LintError>) {
        let author = ctx.author.map(str::trim).filter(|a| !a.is_empty());
        let committer = ctx.committer.map(str::trim).filter(|c| !c.is_empty());

        // Who is judged, how a finding refers to them, and the verb that agrees.
        let judged: Vec<(&str, &str, &str)> = match (author, committer) {
            (Some(a), Some(c)) if a == c => vec![("the author and committer", "are", a)],
            (a, c) => {
                [("the author", a), ("the committer", c)]
                    .into_iter()
                    .filter_map(|(subject, who)| who.map(|w| (subject, "is", w)))
                    .collect()
            },
        };

        for (subject, verb, who) in judged {
            if !self.identities.names_an_agent(who) || glob_matches(permitted, who) {
                continue;
            }
            let why = if permitted.is_empty() {
                format!("permitted in no form under mode `{}`", ctx.mode.as_token())
            } else {
                format!(
                    "it does not match the `{}` pattern `{permitted}`",
                    ctx.mode.as_token()
                )
            };
            let remake = "git rebase --exec 'git commit --amend --allow-empty --no-edit \
                          --reset-author' <upstream>";
            let advice = match (ctx.mode, permitted.is_empty()) {
                (AgentMode::Assistant, _) => {
                    format!(
                        "A commit made with a human in the loop is the human's: set `user.name` \
                         and `user.email` to them, then remake every commit in the range with \
                         `{remake}`, since `--reset-author` on its own repairs only the tip."
                    )
                },
                (AgentMode::Autonomous, true) => {
                    format!(
                        "This mode permits no agent identity: set `user.name` and `user.email` to \
                         a person, then remake every commit in the range with `{remake}`, since \
                         `--reset-author` on its own repairs only the tip."
                    )
                },
                (AgentMode::Autonomous, false) => {
                    format!(
                        "Set `user.name` and `user.email` to an identity matching the pattern, \
                         then remake every commit in the range with `{remake}`, since \
                         `--reset-author` on its own repairs only the tip."
                    )
                },
            };
            out.push(finding(
                ctx,
                1,
                "identity",
                &format!("{subject} {verb} an agent identity, {why}: {who}. {advice}"),
            ));
        }
    }

    /// The active advert pattern set: the configured or default base, plus any
    /// extras, all lowercased for case-insensitive matching.
    fn advert_patterns_active(&self) -> impl Iterator<Item = String> + '_ {
        self.advert_patterns
            .iter()
            .chain(self.extra_patterns.iter())
            .map(|p| p.to_ascii_lowercase())
    }
}

/// The authored lines of a message, numbered from one.
///
/// Comment lines and everything from git's verbose-diff scissors marker are
/// dropped, so a trailer quoted in the commented help text, or one appearing in
/// an attached diff, cannot trip the lint.
fn authored_lines(message: &str) -> Vec<(usize, &str)> {
    message
        .split("# ------------------------ >8")
        .next()
        .unwrap_or(message)
        .lines()
        .enumerate()
        .filter(|(_, l)| !l.starts_with('#'))
        .map(|(i, l)| (i + 1, l))
        .collect()
}

/// The value of a `Co-Authored-By` trailer, if this line is one.
fn coauthor_value(line: &str) -> Option<String> {
    let lower = line.to_ascii_lowercase();
    let at = lower.find("co-authored-by:")?;
    Some(line[at + "co-authored-by:".len() ..].to_string())
}

fn split_list(v: &str) -> Vec<String> {
    v.split(',')
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty())
        .collect()
}

fn finding(ctx: &MessageContext, line: usize, kind: &'static str, message: &str) -> LintError {
    LintError::with_finding_kind(
        ctx.origin.to_string(),
        line,
        LINT_NAME,
        message.to_string(),
        Severity::HARD_ERROR,
        kind,
    )
}

#[cfg(test)]
#[path = "message_attribution_tests.rs"]
mod tests;
